# Site settings
title: Test
email: zhouh08@hotmail.com
description: My Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: 
github_username: onechance
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
# this is the url root of the create page link on the footer page.
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: 
#duoshuo_url:
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: 
disqus_url:
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
